config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  root to: 'tweets#index'
  
  devise_for :users
  
  resources :tweets
  
  resources :users, :only => [:show]
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    belongs_to :user
    
    validates :content, presence: true, allow_blank: false, length: { maximum: 140 } 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  mount_uploader :image, UserImageUploader     
  
  has_many :tweets
  
  # バリデーションを設定
  validates :name, presence: true, uniqueness: true, length: { minimum: 2 } 
  validates :image, presence: true
  validates :profile, presence: true
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_filter :set_search

  def set_search
    @q = Tweet.includes(:user).order(created_at: :desc).ransack(params[:q]) #ransackメソッド推奨
    @tweet = @q.result.page(params[:page]).per(10)
  end


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image, :profile])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image, :profile])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    
    def index
      @input_tweet = Tweet.new
    end
    
    def show
      @tweet = Tweet.find(params[:id])
    end
   
    def create
      tweet = Tweet.new
      tweet.attributes = tweet_params
      tweet.user_id = current_user.id
      if tweet.valid? # バリデーションチェック
        tweet.save!
        redirect_to action: :index
      else
        @input_tweet = Tweet.new(tweet_params)
        flash[:alert] = tweet.errors.full_messages
        render action: :index
      end
    end
    
    def edit
      @tweet = Tweet.find(params[:id])
    end
    
    def update
     @tweet = Tweet.find(params[:id])
    #  tweet = Tweet.find(params[:id])
     @tweet.attributes = tweet_params
       if @tweet.valid? # バリデーションチェック
          @tweet.save!
          redirect_to action: :show
       else
         flash[:alert] = @tweet.errors.full_messages
         render action: :show
       end
    end
    
    def destroy
      @tweet = Tweet.find(params[:id])
      @tweet.destroy
      redirect_to action: :index
    end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    
  def mypost?(tweet)
    tweet.user.id == current_user.id
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElitesTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Twitter", root_path, class: "navbar-brand" %>
    </div>
    <%= search_form_for @q, url: root_path, html: { class: 'navbar-form navbar-left' } do |f| %>
      <div class="form-group">
        <%= f.search_field :content_cont, class: 'form-control', placeholder: '検索' %>
      </div>
      <%= f.submit class: 'btn btn-default' %>
    <% end %> 
      <ul class="nav navbar-nav navbar-right">
        <!-- ここから追加 -->
        <% if user_signed_in? %>
          <li><%= link_to user_path(current_user.id) do %><%= current_user.name %><% end %></li>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
        <!-- ここまで追加 -->
      </ul>
  </div><!-- /.container-fluid -->
</nav>

  <p class="notice"><%= notice %></p>

<div class="container ol-md-offset-2 col-md-8 col-md-offset-2  col-sm-12">
  <div class="row">
      <%= yield %>
  </div>
</div>  

</body>
</html>

app/views/tweets/edit.html.erb
<div class="wrapper tweet_wrapper">
  <div class="input">
    <%= form_for @tweet do |f| %>
      <div class="form-group">
        <%= f.text_area :content, placeholder: "本文は140字以内で投稿", class: 'form-control', rows: 3 %>
      </div>
      <div class="actions clearfix">
        <div class="alert">
          <% if flash[:alert] %>
            <% flash[:alert].each do |message| %>
              <p class="alert"><%= message %></p>
            <% end %>
          <% end %>
        </div>          
        <div class="post">
          <%= f.submit '更新', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>  

<div class="del">
  <%= button_to '削除', tweet_path(@tweet), method: :delete, class: 'btn btn-danger', data: {confirm: '削除してよろしいですか？'}  %>
</div>

app/views/tweets/index.html.erb
<div class="wrapper tweet_wrapper">

  <!-- メッセージ入力 -->
  <div class="input">
    <%= form_for @input_tweet do |f| %>
      <div class="form-group">
        <%= f.text_area :content, placeholder: "本文は140字以内で投稿", class: 'form-control', rows: 3 %>
      </div>
      <div class="actions clearfix">
        <div class="alert">
          <% if flash[:alert] %>
            <% flash[:alert].each do |message| %>
              <p class="alert"><%= message %></p>
            <% end %>
          <% end %>
        </div>          
        <div class="post">
          <%= f.submit '投稿', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
  <!-- タイムライン -->
  <div class="tweet">
    <% @tweet.each do |t| %>
      <div class="per <%= 'mine' if t.user.id == current_user.id %>">
        <p class="icon">
            <%= image_tag t.user.image.url %>
        </p>
        <p class="content">
          <%= link_to user_path(t.user.id) do %><%= t.user.name %><% end %>
          <%= link_to tweet_path(t.id) do %><%= t.created_at %><% end %>
          <br>
          <% if mypost?(t) %>
            <%= link_to edit_tweet_path(t.id) do %>
              <%= t.content %>
            <% end %>
           <% else %>
            <%= t.content %>
          <% end %>
        </p>
      </div>
    <% end %>
    
    <%= paginate @tweet %>
  </div>  
</div>

app/views/tweets/show.html.erb
<div class="wrapper tweet_wrapper">

  <div class="alert">
    <% if flash[:alert] %>
      <% flash[:alert].each do |message| %>
        <p class="alert"><%= message %></p>
      <% end %>
    <% end %>
  </div>  

  <div class="tweet">
      <div class="per <%= 'mine' if @tweet.user.id == current_user.id %>">
        <p class="icon">
            <%= image_tag @tweet.user.image.url %>
        </p>
        <p class="content">
          <%= @tweet.user.name %>
          <%= link_to tweet_path(@tweet.id) do %><%= @tweet.created_at %><% end %>
          <br>
          <% if mypost?(@tweet) %>
            <%= link_to edit_tweet_path(@tweet.id) do %>
              <%= @tweet.content %>
            <% end %>
           <% else %>
            <%= @tweet.content %>
          <% end %>
        </p>
      </div>
  </div> 

</div>

app/views/users/show.html.erb
<div class="wrapper">

  <div class="user">
        <p class="icon">
            <%= image_tag @user.image.url %>
        </p>
        <p class="content">
          【ユーザーネーム】:<%= @user.name %>
          <br>
          【最終ログイン】:<%= @user.last_sign_in_at %>
          <br>
          【プロフィール】:<%= @user.profile %>
        </p>
  </div> 
  
  <div class="user_tweet">
    <% @user.tweets.each do |t| %>
      <div class="per <%= 'mine' if t.user.id == current_user.id %>">
        <p class="icon">
            <%= image_tag t.user.image.url %>
        </p>
        <p class="content">
          <%= link_to user_path(t.user.id) do %><%= t.user.name %><% end %>
          <%= link_to tweet_path(t.id) do %><%= t.created_at %><% end %>
          <br>
          <% if mypost?(t) %>
            <%= link_to edit_tweet_path(t.id) do %>
              <%= t.content %>
            <% end %>
           <% else %>
            <%= t.content %>
          <% end %>
        </p>
      </div>
    <% end %>
    
    <%= paginate @tweet %>
  </div>    

</div>